repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: pretty-format-json
      - id: sort-simple-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.3
          - "prettier-plugin-tailwindcss@0.5.7"
          - "@ianvs/prettier-plugin-sort-imports@4.1.1"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.52.0"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.52.0
          - "eslint-config-prettier@9.0.0"
